// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBf3xCWN_PIsSWhm2ZwzQ48NsaR7kyYa4U',
    appId: '1:192417003533:web:591c6e6989621acab27d44',
    messagingSenderId: '192417003533',
    projectId: 'mob3-uas-klp-05',
    authDomain: 'mob3-uas-klp-05.firebaseapp.com',
    storageBucket: 'mob3-uas-klp-05.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBc98EyKTb-RmYgPKMmtO4dwJSR9Ox6NrI',
    appId: '1:192417003533:android:dbd027a50afa38a3b27d44',
    messagingSenderId: '192417003533',
    projectId: 'mob3-uas-klp-05',
    storageBucket: 'mob3-uas-klp-05.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDccOuRttq_rmgh2BluoW7K-36gdNfvzlI',
    appId: '1:192417003533:ios:df02f47a11cfde13b27d44',
    messagingSenderId: '192417003533',
    projectId: 'mob3-uas-klp-05',
    storageBucket: 'mob3-uas-klp-05.firebasestorage.app',
    iosBundleId: 'com.example.mob3UasKlp05',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDccOuRttq_rmgh2BluoW7K-36gdNfvzlI',
    appId: '1:192417003533:ios:df02f47a11cfde13b27d44',
    messagingSenderId: '192417003533',
    projectId: 'mob3-uas-klp-05',
    storageBucket: 'mob3-uas-klp-05.firebasestorage.app',
    iosBundleId: 'com.example.mob3UasKlp05',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBf3xCWN_PIsSWhm2ZwzQ48NsaR7kyYa4U',
    appId: '1:192417003533:web:13329622cc3e0685b27d44',
    messagingSenderId: '192417003533',
    projectId: 'mob3-uas-klp-05',
    authDomain: 'mob3-uas-klp-05.firebaseapp.com',
    storageBucket: 'mob3-uas-klp-05.firebasestorage.app',
  );
}
